//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by NetBot.rc
//
#define IDD_SHELL_DLG                   101
#define IDD_NETBOT_DIALOG               102
#define IDD_LOGO_DIALOG                 103
#define IDR_MAINFRAME                   128
#define IDI_OL_FILE                     129
#define IDI_OL_REMOTE                   130
#define IDI_OL_PROCESS                  131
#define IDI_OL_DOS                      132
#define IDI_OL_CONFIG                   133
#define IDI_OL_HELP                     134
#define IDI_OL_UPDATE                   135
#define IDI_OL_EXIT                     136
#define IDI_OL_SERVER                   137
#define IDI_OL_HOME                     138
#define IDR_241                         140
#define IDD_PROCESS_DLG                 141
#define IDI_LIST_ONLINE                 142
#define IDD_HELP_DLG                    143
#define IDD_UPDATE_DLG                  144
#define IDD_FILE_DLG                    145
#define IDD_TRANS_DLG                   146
#define IDD_SERVER_DLG                  147
#define IDD_SET_DLG                     148
#define IDI_OL_SCREEN                   149
#define IDD_SCREEN_DLG                  150
#define IDB_FOLDERS                     151
#define IDI_FILE_DIR                    154
#define IDR_FILE_TOOLBAR                158
#define IDB_FILETB_DISABLE              160
#define IDB_FILETB_HOT                  161
#define IDB_FILETB_NORMAL               162
#define IDR_MENU_FILEVIEW               163
#define IDR_MENU_FILERIGHT              164
#define IDR_MENU_ONLINE                 165
#define IDR_ONLINE_TOOLBAR              166
#define IDD_DDOS_DLG                    168
#define IDI_OL_DDOS                     169
#define IDB_LOGO                        172
#define IDR_FSG                         174
#define IDR_UPX                         176
#define IDD_DOWNLOAD_DLG                179
#define IDD_UPLOAD_DLG                  180
#define IDB_BMP_MAIN                    181
#define IDR_MAINTOOLBAR                 184
#define IDR_MENU_MAIN                   187
#define IDR_AVI                         194
#define IDI_LIST_VIDEO                  195
#define IDD_VIDEO_DLG                   196
#define IDD_DDOS1_DLG                   197
#define IDD_FILETRAN_DLG                199
#define IDI_OL_TRANS                    200
#define IDI_FILE_UP                     201
#define IDI_FILE_DOWN                   202
#define IDR_EXE                         203
#define IDR_DLL                         205
#define IDR_SKIN                        206
#define IDR_ORG                         207
#define IDD_DIALOG1                     208
#define IDR_SHELL                       209
#define IDC_OUTLOOK_BAR                 1000
#define IDC_LIST_ONLINE                 1001
#define IDC_STATIC_TITLE                1002
#define IDC_PROCESS_LIST                1003
#define IDC_GETPROCESS_BTN              1004
#define IDC_KILLPROCESS_BTN             1005
#define IDC_PROCESS_STATIC              1006
#define IDC_PRONUM_STATIC               1007
#define IDC_CMDEDIT                     1008
#define IDC_LIST1                       1009
#define IDC_FILELIST                    1009
#define IDC_LIST_LOG                    1009
#define IDC_SVRLOG_LIST                 1009
#define IDC_TASK_LIST                   1009
#define IDC_COMBO1                      1010
#define IDC_COMBO_FTPIP                 1010
#define IDC_COMBO_TYPE1                 1010
#define IDC_COMBO_CMDLINE               1010
#define IDC_EDIT1                       1011
#define IDC_EDIT_PATH                   1011
#define IDC_EDIT_LISTENPORT             1011
#define IDC_EDIT_FTPIP                  1011
#define IDC_EDIT_IP1                    1011
#define IDC_URL                         1011
#define IDC_EXEC_URL                    1011
#define IDC_SRCFILE_EDIT                1011
#define IDC_EDIT_LOCAL                  1011
#define IDC_EDIT_CUSTOMDATA_ANSI        1011
#define IDC_EDIT_CONNECTPASS            1012
#define IDC_EDIT_FTPPORT                1012
#define IDC_EDIT_PORT1                  1012
#define IDC_EDIT2                       1012
#define IDC_OPEN_URL                    1012
#define IDC_EDIT_SHOW                   1012
#define IDC_DSTFILE_EDIT                1012
#define IDC_EDIT_REMOTE                 1012
#define IDC_EDIT_NAME                   1012
#define IDC_EDIT_PARAM1                 1012
#define IDC_BTN_SHELLRUN                1013
#define IDC_EDIT_CONNECTPASS2           1013
#define IDC_COMBO_DNSIP                 1013
#define IDC_EDIT_IP2                    1013
#define IDC_EDIT_CONNECTMAX             1013
#define IDC_EDIT_DISP                   1013
#define IDC_EDIT_PARAM2                 1013
#define IDC_EDIT_CMDLINE                1014
#define IDC_COMBO_FTPPORT               1014
#define IDC_EDIT_PORT2                  1014
#define IDC_EDIT_DESC                   1014
#define IDC_EDIT_CUSTOMDATA_HEX         1014
#define IDC_SHELL_STATICBAR             1015
#define IDC_COMBO_TYPE2                 1015
#define IDC_EDIT_PARAM3                 1015
#define IDC_FILE_STATICBAR              1016
#define IDC_FILE_STATICBAR1             1016
#define IDC_EDIT_IP3                    1016
#define IDC_EDIT_PARAM4                 1016
#define IDC_COMBO_DRIVER                1017
#define IDC_EDIT_PORT3                  1017
#define IDC_COMBO_TYPE3                 1018
#define IDC_FILE_STATICBAR2             1019
#define IDC_EDIT_IP                     1019
#define IDC_DOWNLOADLIST                1020
#define IDC_EDIT_PORT                   1020
#define IDC_COMBO_TYPE                  1021
#define IDC_EDIT_PORT_CUSTOM            1021
#define IDC_EDIT_IP4                    1022
#define IDC_EDIT_PORT7                  1022
#define IDC_BTN_SETSAVE1                1023
#define IDC_EDIT_PORT4                  1023
#define IDC_EDIT_FTPUSER                1024
#define IDC_BTN_SETSAVE2                1024
#define IDC_COMBO_TYPE4                 1024
#define IDC_EDIT_FTPPASS                1025
#define IDC_BTN_SETSAVE3                1025
#define IDC_EDIT_IP5                    1025
#define IDC_EDIT_CC_PARAMX              1025
#define IDC_FTPURL                      1026
#define IDC_EDIT_PORT5                  1026
#define IDC_BTN_SETSAVE4                1026
#define IDC_EDIT_CC_PARAMY              1026
#define IDC_BTN_FTPUPDATE               1027
#define IDC_COMBO_TYPE5                 1027
#define IDC_EDIT_DNSUSER                1028
#define IDC_EDIT_THREAD1                1028
#define IDC_EDIT_DNSPASS                1029
#define IDC_SPIN_THREAD1                1029
#define IDC_EDIT_DNSDOMAIN              1030
#define IDC_EDIT_NUM1                   1030
#define IDC_BTN_DNSUPDATE               1031
#define IDC_SPIN_NUM1                   1031
#define IDC_BTN_ATTACK1                 1032
#define IDC_BTN_STOP1                   1033
#define IDC_EDIT_THREAD2                1034
#define IDC_SPIN_THREAD2                1035
#define IDC_EDIT_NUM2                   1036
#define IDC_SPIN_NUM2                   1037
#define IDC_BTN_ATTACK2                 1038
#define IDC_BTN_STOP2                   1039
#define IDC_EDIT_THREAD3                1040
#define IDC_SPIN_THREAD3                1041
#define IDC_EDIT_NUM3                   1042
#define IDC_SPIN_NUM3                   1043
#define IDC_BTN_ATTACK3                 1044
#define IDC_BTN_STOP3                   1045
#define IDC_EDIT_THREAD                 1046
#define IDC_SPIN_THREAD                 1047
#define IDC_EDIT_THREAD4                1048
#define IDC_PASS                        1049
#define IDC_SPIN_THREAD4                1049
#define IDC_RADIO1                      1050
#define IDC_BTN_ATTACK                  1050
#define IDC_RADIO2                      1051
#define IDC_BTN_STOP                    1051
#define IDC_RADIO3                      1052
#define IDC_EDIT_NUM4                   1052
#define IDC_BTN_ATTACK_CUSTOM           1052
#define IDC_USERNAME                    1053
#define IDC_SPIN_NUM4                   1053
#define IDC_BTN_STOP_CUSTOM             1053
#define IDC_USERPASS                    1054
#define IDC_BTN_ATTACK4                 1054
#define IDC_CREATE                      1055
#define IDC_BTN_STOP4                   1055
#define IDC_OK                          1055
#define IDC_SERVERPROGRESS              1056
#define IDC_EDIT_THREAD5                1056
#define IDC_BTN_URLTEST                 1057
#define IDC_SPIN_THREAD5                1057
#define IDC_EDIT4                       1058
#define IDC_EDIT_URLTEST                1058
#define IDC_EDIT_NUM5                   1058
#define IDC_EDIT5                       1059
#define IDC_EDIT_DNSTEST                1059
#define IDC_SPIN_NUM5                   1059
#define IDC_BTN_DNSTEST                 1060
#define IDC_BTN_ATTACK5                 1060
#define IDC_RADIO4                      1061
#define IDC_BTN_STOP5                   1061
#define IDC_RADIO5                      1062
#define IDC_EDIT_IP6                    1062
#define IDC_BTN_MULEXEC                 1063
#define IDC_EDIT_PORT6                  1063
#define IDC_BTN_MULOPEN                 1064
#define IDC_COMBO_TYPE6                 1064
#define IDC_BTN_MULPOWEROFF             1065
#define IDC_EDIT_THREAD6                1065
#define IDC_BTN_MULREBOOT               1066
#define IDC_SPIN_THREAD6                1066
#define IDC_CHECK1                      1067
#define IDC_CHECK_KEYBORD               1067
#define IDC_EDIT_NUM6                   1067
#define IDC_CHECK_CTRL                  1067
#define IDC_CHECK2                      1068
#define IDC_SPIN_NUM6                   1068
#define IDC_CHECK_WIN7                  1068
#define IDC_DLG_RECT                    1069
#define IDC_BTN_ATTACK6                 1069
#define IDC_BTN_3322                    1070
#define IDC_BTN_STOP6                   1070
#define IDC_STATIC_MYIP                 1071
#define IDC_EDIT_NUM                    1071
#define IDC_CHECK_URLTEST               1072
#define IDC_SPIN_NUM                    1072
#define IDC_CHECK_DNSTEST               1073
#define IDC_PROGRESS_FILE               1073
#define IDC_EDIT_NUM_CUSTOM             1073
#define IDC_SPIN_CC_NUM                 1073
#define IDC_SPIN_NUM_CUSTOM             1074
#define IDC_TRAN_PROGRESS               1075
#define IDC_EDIT_NUM7                   1075
#define IDC_CLOSE_CHECK                 1076
#define IDC_SPIN_NUM7                   1076
#define IDC_FILESIZE_EDIT               1078
#define IDC_CHECK_CLOSE                 1079
#define IDC_PROGRESS_TRAN               1080
#define IDC_WANIP_EDIT                  1081
#define IDC_WANIP_BTN                   1082
#define IDC_CHECK_CLOSEWINDOW           1083
#define IDC_RADIO_COLOR1                1084
#define IDC_RADIO_COLOR2                1085
#define IDC_RADIO_COLOR3                1086
#define IDC_RADIO_COLOR4                1087
#define IDC_STATIC_3322                 1087
#define IDC_PROGRESS_SCREEN             1088
#define IDC_CHECK_SKIN                  1088
#define IDC_BTN_START                   1089
#define IDC_FILETREE                    1093
#define IDC_BTN_TEST                    1094
#define IDC_PROGRESS_VIDEO              1095
#define IDC_BTN_SAVEBMP                 1096
#define IDC_BTN_SELNUM                  1098
#define IDC_EDIT_SELNUM                 1099
#define IDC_BTN_ADDRGO                  1100
#define IDC_BTN_RECORDS                 1101
#define IDC_BTN_RECORDE                 1102
#define IDC_CHECK_AUTOATTACK            1104
#define IDC_CHECK_USESELECT             1105
#define IDC_BTN_REFRESH                 1106
#define IDC_CHECK_USESELECT_CUSTOM      1106
#define IDC_EDIT_URL                    1107
#define IDC_EDIT_CC_URL                 1107
#define IDC_EDIT_URL_CUSTOM             1108
#define IDC_RADIO_TCP                   1109
#define IDC_RADIO_UDP                   1110
#define IDC_EDIT_URL2                   1111
#define IDC_RADIO_ANSI                  1112
#define IDC_RADIO_HEX                   1113
#define IDC_EDIT_THREAD_CUSTOM          1114
#define IDC_SPIN_THREAD_CUSTOM          1115
#define IDC_CHECK_USESELECT2            1116
#define IDC_EDIT_CC_PORT                1117
#define IDC_EDIT_CC_THREAD              1118
#define IDC_SPIN_CC_THREAD              1119
#define IDC_EDIT_CC_NUM                 1120
#define IDC_CHECK_CC_USESEL             1121
#define IDC_BTN_CC_ATTACK               1122
#define IDC_BTN_CC_STOP                 1123
#define IDC_RICHEDIT1                   1125
#define IDC_PIC                         1126
#define ID_FILE_BACKUP                  32771
#define ID_FILE_COPY                    32772
#define ID_FILE_PASTE                   32773
#define ID_FILE_DELETE                  32774
#define ID_FILE_UPLOAD                  32775
#define ID_FILE_DOWNLOAD                32776
#define ID_FILE_REFURSH                 32777
#define ID_FILE_CHGVIEW                 32778
#define ID_MENU_FILEVIEW_BIG            32779
#define ID_MENU_FILEVIEW_SMALL          32780
#define ID_MENU_FILEVIEW_LIST           32781
#define ID_MENU_FILEVIEW_DETAIL         32782
#define ID_FILE_RUNNORMAL               32783
#define ID_FILE_RUNHIDE                 32784
#define ID_ONLINE_POWEROFF              32785
#define ID_ONLINE_REBOOT                32786
#define ID_ONLINE_LOGOFF                32787
#define ID_ONLINE_UNINSTALL             32788
#define ID_MENUITEM32789                32789
#define ID_ONLINE_FILEMANAGE            32794
#define ID_ONLINE_SCREEN                32795
#define ID_ONLINE_PROCESS               32796
#define ID_ONLINE_SHELL                 32797
#define ID_BTN_TONLINE                  32798
#define ID_BTN_TDDOS                    32799
#define ID_BTN_TUPDATE                  32800
#define ID_BTN_TCONFIG                  32801
#define ID_BTN_TSERVER                  32802
#define ID_BTN_TWEBSITE                 32803
#define ID_BTN_TEXIT                    32804
#define ID_BTN_THELP                    32805
#define ID_ONLINE_VIDEO                 32807
#define ID_BTN_TDDOS2                   32808
#define ID_BTN_TDDOS1                   32809
#define ID_BTN_TFILETRAN                32810
#define ID_S_SAVE                       32811
#define ID_S_EXIT                       32813
#define ID_S_HELP                       32814
#define ID_S_ABOUT                      32815
#define ID_S_CLEAR                      32816

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        212
#define _APS_NEXT_COMMAND_VALUE         32817
#define _APS_NEXT_CONTROL_VALUE         1128
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
